version: v1.1.0
serve:
  public:
    port: 4433
    cors:
      enabled: false
  admin:
    port: 4434 

selfservice:
  methods:
    link:
      enabled: false
    password:
      enabled: true
      config:
        min_password_length: 15
    code:
      enabled: true
      config:
        lifespan: 24h
        max_submissions: 5

  flows:
    verification:
      enabled: false
    recovery: 
      enabled: true
      ui_url: http://placeholder/recovery
      use: code 
    error:
      ui_url: http://placeholder/error
    settings:
      ui_url: http://placeholder/settings
      privileged_session_max_age: 15m
    logout:
      after:
        default_browser_return_url: http://placeholder/login
    login:
      ui_url: http://placeholder/login

session:
  lifespan: 24h
  cookie:
    domain: irboard.local
    name: irboard_session
    same_site: Lax

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 32

courier:
  delivery_strategy: smtp
  smtp:
    connection_uri: smtp://mailpit:1025/?skip_ssl_verify=true&disable_starttls=true
    from_name: IR-Board System
    from_address: no-reply@ir-board.com
  templates:
    recovery_code:
      valid:
        email:
          subject: file:///etc/config/kratos/templates/recovery/valid/subject.gotmpl
          body:
            html: file:///etc/config/kratos/templates/recovery/valid/body.html.gotmpl
            plaintext: file:///etc/config/kratos/templates/recovery/valid/body.txt.gotmpl