sonar.projectKey=Y4vra_IRBoard_Frontend
sonar.organization=y4vra
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=src/tests/**, **/node_modules/**, **/dist/**, **/vite-env.d.ts, src/vite-env.d.ts

sonar.tests=src/tests
sonar.test.inclusions=src/tests/**/*.test.tsx, src/tests/**/*.test.ts

sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8