networks:
  public:
    driver: bridge
  internal:
    driver: bridge

services:
  # --- GATEWAY ---
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public

  # --- MIGRATION (PREPARE ORY TABLES) ---
  keto-migrate:
    image: oryd/keto:v25.4.0
    depends_on:
      keto-db:
        condition: service_healthy
    environment:
      - DSN=postgres://${KETO_DB_USER}:${KETO_DB_PASSWORD}@keto-db:5432/${KETO_DB_NAME}?sslmode=disable
    volumes:
      - ./config/keto:/etc/config/keto
    command: -c /etc/config/keto/keto.yaml migrate up --yes
    networks:
      - internal
  kratos-migrate:
    image: oryd/kratos:v25.4.0
    environment:
      - DSN=postgres://${KRATOS_DB_USER}:${KRATOS_DB_PASSWORD}@kratos-db:5432/${KRATOS_DB_NAME}?sslmode=disable
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yaml migrate sql -e --yes
    depends_on:
      kratos-db:
        condition: service_healthy
    networks:
      - internal

  # --- IDENTITY (ORY) ---
  kratos-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${KRATOS_DB_USER}
      - POSTGRES_PASSWORD=${KRATOS_DB_PASSWORD}
      - POSTGRES_DB=${KRATOS_DB_NAME}
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KRATOS_DB_USER} -d ${KRATOS_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data_kratos:/var/lib/postgresql/data
  keto-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${KETO_DB_USER}
      - POSTGRES_PASSWORD=${KETO_DB_PASSWORD}
      - POSTGRES_DB=${KETO_DB_NAME}
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KETO_DB_USER} -d ${KETO_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data_keto:/var/lib/postgresql/data

  kratos:
    image: oryd/kratos:v25.4.0
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
      kratos-db:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    environment:
      - DSN=postgres://${KRATOS_DB_USER}:${KRATOS_DB_PASSWORD}@kratos-db:5432/${KRATOS_DB_NAME}?sslmode=disable
      - SERVE_PUBLIC_BASE_URL=http://${AUTH_DOMAIN}/
      - SERVE_ADMIN_BASE_URL=http://kratos:4434/
      - SESSIONS_COOKIE_SECURE=false
      - SESSIONS_COOKIE_DOMAIN=${DOMAIN_NAME}
      - SELFSERVICE_ALLOWED_RETURN_URLS=http://${DOMAIN_NAME}
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=http://${DOMAIN_NAME}/home
      - SELFSERVICE_FLOWS_ERROR_UI_URL=http://${DOMAIN_NAME}/error
      - SELFSERVICE_FLOWS_LOGIN_UI_URL=http://${DOMAIN_NAME}/login
      - SELFSERVICE_FLOWS_REGISTRATION_UI_URL=http://${DOMAIN_NAME}/registration
      - SELFSERVICE_FLOWS_SETTINGS_UI_URL=http://${DOMAIN_NAME}/settings
      - SELFSERVICE_FLOWS_RECOVERY_UI_URL=http://${DOMAIN_NAME}/setup-password
      - SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL=http://${DOMAIN_NAME}/login
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yaml --dev --watch-courier
    networks:
      - internal

  keto:
    image: oryd/keto:v25.4.0
    depends_on:
      keto-migrate:
        condition: service_completed_successfully
      keto-db:
        condition: service_healthy
    environment:
      - DSN=postgres://${KETO_DB_USER}:${KETO_DB_PASSWORD}@keto-db:5432/${KETO_DB_NAME}?sslmode=disable
    volumes:
      - ./config/keto:/etc/config/keto
    command: serve -c /etc/config/keto/keto.yaml
    networks:
      - internal

  oathkeeper:
    image: oryd/oathkeeper:v25.4.0
    depends_on:
      - kratos
      - keto
    environment:
      - AUTHENTICATORS_COOKIE_SESSION_CONFIG_CHECK_SESSION_URL=http://kratos:4433/sessions/whoami
      - AUTHORIZERS_REMOTE_JSON_CONFIG_REMOTE=http://keto:4466/relation-tuples/check/openapi
      - ERRORS_HANDLERS_REDIRECT_CONFIG_TO=http://${DOMAIN_NAME}/login
    volumes:
      - ./config/oathkeeper:/etc/config/oathkeeper
    command: serve proxy -c /etc/config/oathkeeper/oathkeeper.yaml
    networks:
      - public
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oathkeeper.rule=Host(`${AUTH_DOMAIN}`) || Host(`${API_DOMAIN}`) || Host(`grafana.${DOMAIN_NAME}`)"
      - "traefik.http.services.oathkeeper.loadbalancer.server.port=4455"
      - "traefik.docker.network=irboard_public"

  # --- DEVELOPMENT ONLY, INSERTS ADMIN USER FOR FIRST TIME USE ON KRATOS, KETO, AND BACKEND ---
  initial-setup-admin:
    image: alpine:3.23.3
    depends_on:
      kratos:
        condition: service_started
      keto:
        condition: service_started
      backend-db:
        condition: service_healthy
    networks:
      - internal
    environment:
      - KRATOS_URL=http://kratos:4434/admin/identities
      - KETO_URL=http://keto:4467/admin/relation-tuples
      - DB_USER=${RMS_DB_USER}
      - DB_PASS=${RMS_DB_PASSWORD}
      - DB_NAME=${RMS_DB_NAME}
      - ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
      - ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
      - ADMIN_NAME=${INITIAL_ADMIN_NAME}
      - ADMIN_SURNAME=${INITIAL_ADMIN_SURNAME}
    entrypoint: /bin/sh -c
    command:
      - | 
        apk add --no-cache curl jq postgresql-client
        export PGPASSWORD="$$DB_PASS"
        DB_CON_STR="postgresql://$$DB_USER:$$DB_PASS@backend-db:5432/$$DB_NAME"
        sleep 10;
        cat <<EOF > ./file.json
        {
          "schema_id": "default",
          "traits": {
            "email": "${INITIAL_ADMIN_EMAIL}",
            "name": "${INITIAL_ADMIN_NAME}",
            "surname": "${INITIAL_ADMIN_SURNAME}",
            "is_admin": true
          },
          "credentials": {
            "password": {
              "config": {
                "password": "${INITIAL_ADMIN_PASSWORD}"
              }
            }
          }
        }
        EOF
        USER_ID=$(curl -X POST $$KRATOS_URL -H "Content-Type: application/json" -d @file.json | jq -r '.id')
        if [ "$$USER_ID" != "null" ] && [ -n "$$USER_ID" ]; then
          echo "Admin user correctly added to Kratos."

          curl -X PUT $$KETO_URL \
            -H "Content-Type: application/json" \
            -d "{
              \"namespace\": \"System\",
              \"object\": \"main\",
              \"relation\": \"admins\",
              \"subject_id\": \"$$USER_ID\"
            }"
          echo "Admin user correctly added to Keto."

          echo "Waiting for springboot to setup the entity database..."
          until psql "$$DB_CON_STR" -c "SELECT 1 FROM app_user LIMIT 1;" > /dev/null 2>&1; do
            sleep 2
          done
          echo "Tablas detectadas, procediendo con la inyección..."

          psql "$$DB_CON_STR" -c "INSERT INTO app_user (ory_id, email, name, surname) \
            VALUES ('$$USER_ID', '${INITIAL_ADMIN_EMAIL}', '${INITIAL_ADMIN_NAME}', '${INITIAL_ADMIN_SURNAME}') \
            ON CONFLICT (ory_id) DO NOTHING;"
          
          echo "Admin user correctly added to backend-db."
        else
          echo "Error: Unable to obtain adminId from Kratos response."
        fi

  # --- BUSINESS LOGIC ---
  backend-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${RMS_DB_USER}
      - POSTGRES_PASSWORD=${RMS_DB_PASSWORD}
      - POSTGRES_DB=${RMS_DB_NAME}
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${RMS_DB_USER} -d ${RMS_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
    - db_data_rms:/var/lib/postgresql/data

  backend:
    image: maven:3.9.6-eclipse-temurin-21 # [PROD] substitute for build: ./backend
    depends_on:
      backend-db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    environment:
      - KETO_READ_URL=http://keto:4466
      - KETO_WRITE_URL=http://keto:4467
      - SPRING_DATASOURCE_URL=jdbc:postgresql://backend-db:5432/${RMS_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${RMS_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${RMS_DB_PASSWORD}
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    networks:
      - internal
    working_dir: /app # [PROD] remove for production, this allows hot-reload
    command: mvn spring-boot:run # [PROD] remove for production, this allows hot-reload

  frontend:
    build: 
      context: ./frontend
      target: build-stage # [PROD] remove for production
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 # [PROD] remove for production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_DOMAIN_NAME=${DOMAIN_NAME}
      - VITE_AUTH_DOMAIN=${AUTH_DOMAIN}
      - VITE_API_DOMAIN=${API_DOMAIN}
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173" # Default Vite port for Dev mode. Update to 80 for Production-stage (Nginx).

  # --- MAIL SERVER ---
  mailpit:
    image: axllent/mailpit:v1.29
    ports:
      - "8025:8025" 
      - "1025:1025" 
    networks:
      - internal

  # --- OBSERVABILITY ---
  grafana:
    image: grafana/grafana:12.3.5
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - internal
  
  
  loki:
    image: grafana/loki:3.5.12
    networks:
      - internal

  promtail:
    image: grafana/promtail:3.5.12
    container_name: promtail
    user: root # Possible threat, but added as hardening the project's observability is beyond the project's scope
    volumes:
      - ./config/promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - internal
    depends_on:
      - loki

volumes: # [PROD] remove volumes in production
  db_data_kratos:
  db_data_keto:
  db_data_rms: