@startuml ArchitectureC2
title Architecture diagram (IR-Board)

actor user

' Redes (Networks)
package "Network: public" #line.dotted {
    [RMS Frontend] as front
    [Traefik] as gateway
}

package "Network: internal" #AliceBlue {
    [Ory Oathkeeper] as proxy
    [Ory Kratos] as kratos
    [Ory Keto] as keto
    [RMS Backend] as backend
    [Loki]
    [Grafana]
    [Promtail]
    
    database "PostgreSQL (RMS)" as db_rms
    database "PostgreSQL (Identity)" as db_auth
    database "PostgreSQL (Permissions)" as db_perm
}

' Conexiones de tráfico
user -down-> gateway
gateway -down-> front 
gateway -down--> proxy 

' Consultas internas Ory
proxy -> kratos 
proxy -left-> keto 
proxy .> Grafana

' Paso final al Backend
proxy -down-> backend

' Persistencia
backend .> keto : Write Tuples (GRPC)

backend -down-> db_rms
kratos -down-> db_auth
keto -down-> db_perm

' Observabilidad

Grafana --> Loki
Promtail ..> Loki : deliver logs
Promtail ..> kratos
Promtail ..> keto
Promtail ..> backend
Promtail .left.> proxy


@enduml