@startuml RequirementStates
title Lifecycle of a Requirement (IR-Board)

state PendingApproval{
  state Reviewed : By default
  state PendingReview {
    PendingReview : Flagged due to changes in 
    PendingReview : linked Stakeholders/Docs/Requirements
  }
}

state Approved
state Closed: Finished, implemented

state Deactivated : Read-only mode

state Removed: Archived, hidden from view


' Transiciones
[*] -down-> PendingApproval : Requirement is created and saved

PendingReview -up-> Reviewed : Review completed (modifying it or accepting it)

PendingApproval -right-> Approved 
Approved -up-> PendingApproval : modified

Approved -right-> Closed : completed
Closed -left-> PendingApproval : modified

PendingApproval -down-> Deactivated 
Deactivated -up-> PendingApproval

Deactivated -down-> Removed
Removed -up-> Deactivated

Removed -down->[*]

@enduml