- id: "allow-frontend-static"
  match:
    methods: ["GET"]
    url: "http://irboard.local/<.*>"
  authenticators: [{ handler: "noop" }]
  authorizer: { handler: "allow" }
  mutator: { handler: "noop" }
  upstream:
    url: "http://frontend:80"

- id: "api-backend-protected"
  match:
    methods: ["GET", "POST", "PUT", "DELETE"]
    url: "http://api.irboard.local/api/<.*>"
  authenticators: [{ handler: "cookie_session" }]
  authorizer: { handler: "allow" }
  mutator: { handler: "header" }
  upstream:
    url: "http://backend:8080"