spring.application.name=IRBoard-backend
keto.read.url=${KETO_READ_URL}
keto.write.url=${KETO_WRITE_URL}
kratos.admin.url=${KRATOS_ADMIN_URL}
kratos.admin.api.key=${KRATOS_ADMIN_API_KEY}
minio.url=${OBJ_STORAGE_URL}
minio.access-key=${OBJ_STORAGE_USER}
minio.secret-key=${OBJ_STORAGE_PASS}
minio.bucket-name=documents
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${RMS_DB_NAME:rms_db}
spring.datasource.username=${RMS_DB_USER:postgres}
spring.datasource.password=${RMS_DB_PASSWORD:tu_password}
spring.datasource.driver-class-name=org.postgresql.Driver

server.forward-headers-strategy=native

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/v1

# DEBUGGING
logging.level.org.hibernate.boot.model.internal=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG