spring.application.name=IRBoard-backend

server.servlet.context-path=/v1
spring.main.lazy-initialization=true
server.forward-headers-strategy=native
spring.jpa.open-in-view=false

# Drivers config
keto.read.url=${KETO_READ_URL}
keto.write.url=${KETO_WRITE_URL}
kratos.admin.url=${KRATOS_ADMIN_URL}
kratos.public.url=${KRATOS_PUBLIC_URL}
kratos.admin.api.key=${KRATOS_ADMIN_API_KEY}
minio.url=${OBJ_STORAGE_URL}
minio.access-key=${OBJ_STORAGE_USER}
minio.secret-key=${OBJ_STORAGE_PASS}
minio.bucket-name=documents
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# DB
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${RMS_DB_NAME:rms_db}
spring.datasource.username=${RMS_DB_USER:postgres}
spring.datasource.password=${RMS_DB_PASSWORD:tu_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10

# DEBUGGING
#logging.level.org.hibernate.boot.model.internal=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG

# OBSERVABILITY
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=backend